import { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
    id: 'saga-001',
    title: 'Gulabi Baugh Powder Blue Chikankari Suit Set (Unstitched)',
    subtitle: '100% Unstitched Cotton Fabric with Paisley Neck Chikankari Embroidery',
    price: 2299,
    originalPrice: 3499,
    description: 'Immerse yourself in authentic Jaipur luxury with our Gulabi Baugh Powder Blue Unstitched Suit Set. Featuring delicate white Chikankari hand-embroidery along the neckline and sleeves, this 100% breathable pure cotton unstitched fabric set is ready to be tailored to your custom measurements.',
    fabric: '100% Premium Unstitched Chanderi Cotton (Top: 2.5m, Bottom: 2.5m, Dupatta: 2.25m)',
    craft: 'Authentic Lucknowi & Jaipuri Embroidery',
    care: 'Gentle Hand Wash or Dry Clean Only',
    color: 'Powder Blue',
    colorHex: '#A5C4D4',
    images: ['/images/products/powder-blue-kurti.jpg'],
    sizes: ['Unstitched'],
    tags: ['Bestseller', 'Chikankari', 'Unstitched'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 42,
  },
  {
    id: 'saga-002',
    title: 'Amer Turquoise Handblock Floral Suit Set (Unstitched)',
    subtitle: 'Vibrant Emerald Teal Unstitched Cotton Fabric with White Thread Work',
    price: 1899,
    originalPrice: 2799,
    description: 'Inspired by the vibrant colors of Amer Fort, this striking turquoise unstitched suit fabric set is crafted from ultra-soft cotton. It features a geometrically detailed white embroidered yoke and borders, perfect for custom boutique stitching.',
    fabric: '100% Soft Malmal Unstitched Cotton (Top: 2.5m, Bottom: 2.5m)',
    craft: 'Jaipur Handblock Motif Work',
    care: 'Hand Wash separately in cold water',
    color: 'Emerald Teal',
    colorHex: '#14A098',
    images: ['/images/products/emerald-teal-kurti.jpg'],
    sizes: ['Unstitched'],
    tags: ['New Arrival', 'Festive Collection', 'Unstitched'],
    inStock: true,
    rating: 4.8,
    reviewsCount: 28,
  },
  {
    id: 'saga-003',
    title: 'Rani Pink Royalty Suit & Dupatta Set (Unstitched)',
    subtitle: '3-Piece Magenta Unstitched Suit Material with Chiffon Dupatta',
    price: 2699,
    originalPrice: 3999,
    description: 'A regal royal pink unstitched ensemble showcasing Jaipuri lattice grid embroidery. Includes generous unstitched fabric length for kurti & trousers along with a matching lightweight chiffon dupatta.',
    fabric: 'Premium Unstitched Mulmul Cotton & Chiffon Dupatta',
    craft: 'Traditional Jaipuri Resham Thread Work',
    care: 'Dry Clean Recommended',
    color: 'Rani Pink',
    colorHex: '#E04886',
    images: ['/images/products/rani-pink-kurti.jpg'],
    sizes: ['Unstitched'],
    tags: ['Royal Edition', '3-Piece Set', 'Unstitched'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 56,
  },
  {
    id: 'saga-004',
    title: 'Jaipur Pearl White & Royal Indigo Suit Set (Unstitched)',
    subtitle: 'Pristine White Unstitched Cotton Fabric with Royal Blue Embroidery',
    price: 1999,
    originalPrice: 2999,
    description: 'The epitome of classic Jaipur minimalist charm. Crisp ivory white unstitched cotton fabric accented with rich royal indigo floral motif embroidery on the neck and sleeve panels.',
    fabric: '100% Unstitched Organic Cotton',
    craft: 'Jaipur Indigo Thread Craft',
    care: 'Machine Wash Cold on Gentle Cycle',
    color: 'Ivory White & Royal Blue',
    colorHex: '#F7F7F7',
    images: ['/images/products/ivory-blue-kurti.jpg'],
    sizes: ['Unstitched'],
    tags: ['Classic White', 'Unstitched Material'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 39,
  },
  {
    id: 'saga-005',
    title: 'Gulabi Rose Chikankari 3-Piece Suit Set (Unstitched)',
    subtitle: 'Unstitched Soft Pink Hand-Embroidered Fabric with Sheer Organza Dupatta',
    price: 2499,
    originalPrice: 3699,
    description: 'Radiate timeless Jaipur grace with our Gulabi Rose Unstitched Chikankari Suit Set. Crafted in soft pastel pink featuring intricate white hand-embroidered Chikankari motifs. Paired with a matching organza dupatta.',
    fabric: '100% Premium Unstitched Cotton & Organza Dupatta',
    craft: 'Authentic Lucknowi & Jaipuri Hand Embroidery',
    care: 'Dry Clean or Gentle Cold Hand Wash',
    color: 'Gulabi Pink',
    colorHex: '#EC5B89',
    images: ['/images/products/pink-chikankari-kurti.jpg'],
    sizes: ['Unstitched'],
    tags: ['New Arrival', 'Chikankari', '3-Piece Set', 'Unstitched'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 34,
  },
];

