import { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
    id: 'saga-test-001',
    title: 'Live Pixel & Gateway Test Fabric Sample (₹1 Test Order)',
    subtitle: 'System Verification Order - 100% Refundable / Live Gateway Test',
    price: 1,
    originalPrice: 99,
    description: 'This is an official ₹1 verification product to test live Razorpay payment processing and Meta Pixel Purchase event attribution.',
    fabric: '100% Pure Cotton Sample Swatch',
    craft: 'Chikankari Handwork Sample',
    care: 'Hand Wash',
    color: 'Test Sample',
    colorHex: '#9E6962',
    images: ['/images/products/short-kurti-1.jpg'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['Live Test', '₹1 Verification'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 1,
  },
  {
    id: 'saga-017',
    title: 'Emerald Bottle Green Stitched Suit Set',
    subtitle: 'Pure Cotton Long Kurti with Geometric Ajrakh Printed Dupatta & Trousers (Ready to Wear)',
    price: 2400,
    originalPrice: 3499,
    description: 'Exude understated grace in this deep Emerald Bottle Green 3-Piece Stitched Suit Set. Features an intricately embroidered yoke with traditional block-inspired motifs, coordinating tailored straight trousers, and a luxurious printed dupatta with ethnic border accents. Tailored from 100% premium breathable cotton for day-to-evening comfort.',
    fabric: '100% Breathable Pure Cotton & Mulmul Dupatta (Stitched 3-Piece Set)',
    craft: 'Embroidered Yoke & Ajrakh Geometric Print',
    care: 'Gentle Hand Wash in Cold Water',
    color: 'Emerald Bottle Green',
    colorHex: '#1B4D3E',
    images: ['/images/products/stitched-suit-emerald-green.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['New Arrival', 'Stitched Suit', '3-Piece Set', 'Bestseller'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 36,
  },
  {
    id: 'saga-018',
    title: 'Navy Blue & Crimson Maroon Ajrakh Stitched Suit Set',
    subtitle: 'Midnight Navy Pure Cotton Long Kurti with Rich Ajrakh Handblock Print Dupatta & Pants',
    price: 2400,
    originalPrice: 3499,
    description: 'A regal contrast of rich midnight navy blue and earthy crimson red. This ready-to-wear 3-piece suit set features an ornate floral-geometric embroidered neck yoke, matching navy straight trousers, and a statement Ajrakh block-printed dupatta draped to perfection.',
    fabric: '100% Pure Cotton with Cotton Dupatta (Stitched 3-Piece Set)',
    craft: 'Ajrakh Handblock Print & Neckline Embroidery',
    care: 'Dry Clean or Gentle Cold Hand Wash',
    color: 'Navy Blue & Crimson Maroon',
    colorHex: '#1B263B',
    images: ['/images/products/stitched-suit-navy-maroon.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['New Arrival', 'Stitched Suit', '3-Piece Set', 'Festive Edit'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 42,
  },
  {
    id: 'saga-019',
    title: 'Royal Indigo Blue Stitched Suit Set',
    subtitle: 'Deep Indigo Long Kurti with Embroidered Yoke & Matching Geometric Print Dupatta',
    price: 2400,
    originalPrice: 3499,
    description: 'Timeless ethnic elegance in rich royal indigo blue. Designed with fine geometric neck yoke embroidery, 3/4th sleeves with printed border cuffs, tailored matching trousers, and a breezy all-over printed dupatta. Perfect for office wear, gatherings, and festive celebrations.',
    fabric: '100% Soft Breathable Pure Cotton (Stitched 3-Piece Set)',
    craft: 'Traditional Yoke Embroidery & Geometric Block Print',
    care: 'Gentle Hand Wash Cold',
    color: 'Royal Indigo Blue',
    colorHex: '#1E3A5F',
    images: ['/images/products/stitched-suit-royal-indigo.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['New Arrival', 'Stitched Suit', '3-Piece Set', 'Royal Edit'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 28,
  },
  {
    id: 'saga-020',
    title: 'Ivory Cream & Ochre Embroidered Stitched Suit Set',
    subtitle: 'Pristine Ivory Long Kurti with Handcrafted Ochre-Rust Neck Yoke & Hemline Embroidery',
    price: 2400,
    originalPrice: 3499,
    description: 'Radiate artisanal poise in this pristine ivory cream ready-to-wear kurti pant suit set. Adorned with heritage arch-inspired ochre and rust thread embroidery along the neckline, sleeve cuffs, and bottom hemline. Tailored in a comfortable regular fit with matching straight trousers.',
    fabric: '100% Premium Khadi Cotton (Stitched Suit Set)',
    craft: 'Artisanal Resham Thread Embroidery',
    care: 'Gentle Cold Wash or Dry Clean',
    color: 'Ivory Cream & Rust Ochre',
    colorHex: '#F8F5EE',
    images: ['/images/products/stitched-suit-ivory-cream.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['New Arrival', 'Stitched Suit', '3-Piece Set', 'Royal Edit'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 39,
  },
  {
    id: 'saga-021',
    title: 'Blush Rose Pink Stitched Suit Set',
    subtitle: 'Vibrant Rose Pink Long Kurti with Subtle Booti Motif & Sheer Flowing Dupatta',
    price: 2400,
    originalPrice: 3499,
    description: 'A charming feminine silhouette in cheerful blush rose pink. Features buttoned placket detailing, delicate white booti prints across the kurti body, coordinating straight-cut pants, and an ethereal lightweight printed dupatta. Ready to wear and effortlessly stylish.',
    fabric: '100% Pure Fine Cotton & Mulmul Dupatta (Stitched 3-Piece Set)',
    craft: 'Handblock Booti Print & Potli Button Detailing',
    care: 'Gentle Hand Wash in Cold Water',
    color: 'Blush Rose Pink',
    colorHex: '#EC4899',
    images: ['/images/products/stitched-suit-rose-pink.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['New Arrival', 'Stitched Suit', '3-Piece Set', 'Festive Edit'],
    inStock: true,
    rating: 4.8,
    reviewsCount: 31,
  },
  {
    id: 'saga-022',
    title: 'Slate Grey Multi-Stripe Handblock Stitched Suit Set',
    subtitle: 'Contemporary Vertical Stripe Long Kurti with Chakra Block Motifs & Matching Dupatta',
    price: 2400,
    originalPrice: 3499,
    description: 'Modern contemporary aesthetics meet traditional Indian block craft. Features striking slate grey, crimson, and ivory vertical stripes accented with medallion chakra motifs, matching printed trousers, and a full-length statement dupatta for an elongated, flattering silhouette.',
    fabric: '100% Breathable Pure Cotton (Stitched 3-Piece Set)',
    craft: 'Authentic Handblock Stripe & Chakra Print',
    care: 'Gentle Cold Wash',
    color: 'Slate Grey & Crimson',
    colorHex: '#4A5568',
    images: ['/images/products/stitched-suit-slate-grey.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['New Arrival', 'Stitched Suit', '3-Piece Set', 'Handblock'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 25,
  },
  {
    id: 'saga-023',
    title: 'Crimson Maroon Ajrakh Stitched Suit Set',
    subtitle: 'Deep Maroon Red V-Neck Long Kurti with Side Border Embroidery & Ajrakh Dupatta',
    price: 2400,
    originalPrice: 3499,
    description: 'Rich, regal, and festive. Crafted in deep crimson maroon pure cotton with a sharp embroidered V-neckline, hanging tassel accent, side-slit border embroidery, matching trousers, and an authentic monochrome Kalamkari/Ajrakh print dupatta with chevron and floral borders.',
    fabric: '100% Premium Pure Cotton & Ajrakh Dupatta (Stitched 3-Piece Set)',
    craft: 'V-Neck Hand Embroidery & Ajrakh Block Print',
    care: 'Dry Clean Recommended',
    color: 'Crimson Maroon Red',
    colorHex: '#800020',
    images: ['/images/products/stitched-suit-crimson-maroon.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['New Arrival', 'Stitched Suit', '3-Piece Set', 'Bestseller'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 47,
  },
  {
    id: 'saga-001',
    title: 'Royal Indigo White Chikankari Short Kurti',
    subtitle: '100% Pure Cotton Short Kurti with Royal Blue Neck & Sleeve Chikankari',
    price: 1399,
    originalPrice: 1999,
    description: 'Handcrafted Royal Indigo White Chikankari Short Kurti. Crafted from ultra-breathable pure cotton with delicate royal blue Chikankari hand embroidery along the neckline, sleeves, and hem. Stitched in a relaxed, elegant fit.',
    fabric: '100% Breathable Pure Cotton (Stitched Kurti)',
    craft: 'Authentic Lucknowi Chikankari Embroidery',
    care: 'Gentle Hand Wash in Cold Water',
    color: 'Pristine White & Royal Blue',
    colorHex: '#1E3A8A',
    images: ['/images/products/short-kurti-1.jpg', '/images/products/short-kurti-2.jpg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['Bestseller', 'Chikankari', 'Short Kurti'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 48,
  },
  {
    id: 'saga-002',
    title: 'Mint Emerald Chikankari Short Kurti',
    subtitle: 'Soft White Pure Cotton Short Kurti with Refreshing Emerald Green Threadwork',
    price: 1449,
    originalPrice: 2099,
    description: 'Radiate fresh elegance with this Mint Emerald Chikankari Short Kurti. Meticulously embroidered with botanical green thread patterns on light-as-air pure cotton fabric. Perfect for daily and festive styling.',
    fabric: '100% Soft Mulmul Pure Cotton (Stitched Kurti)',
    craft: 'Traditional Hand Chikankari',
    care: 'Gentle Hand Wash or Dry Clean',
    color: 'Pristine White & Emerald Green',
    colorHex: '#059669',
    images: ['/images/products/short-kurti-3.jpg', '/images/products/short-kurti-4.jpg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['Festive Edit', 'Chikankari', 'Short Kurti'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 41,
  },
  {
    id: 'saga-003',
    title: 'Rose Gold Beige Chikankari Short Kurti',
    subtitle: 'Elegant Ivory Cotton Short Kurti with Soft Tan & Rose Gold Threadwork',
    price: 1449,
    originalPrice: 2099,
    description: 'Delicate pastel luxury for all occasions. Features subtle resham threadwork hand-embroidered on soft white pure cotton kurti. Comfortable, breathable, and versatile.',
    fabric: '100% Pure Organic Cotton (Stitched Kurti)',
    craft: 'Lucknowi Resham Chikankari',
    care: 'Gentle Cold Wash',
    color: 'Pristine White & Soft Beige',
    colorHex: '#D97706',
    images: ['/images/products/short-kurti-5.jpg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['Royal Edit', 'Chikankari', 'Short Kurti'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 29,
  },
  {
    id: 'saga-004',
    title: 'Mustard & Red Handblock 3-Piece Unstitched Suit Set',
    subtitle: 'Vibrant Mustard Yellow Unstitched Fabric with Red Bottom & Matching Dupatta',
    price: 1399,
    originalPrice: 1999,
    description: 'A striking 3-piece ethnic unstitched suit set featuring traditional hand block motifs on bright mustard yellow cotton fabric, paired with red bottom material and a lightweight flowy dupatta.',
    fabric: '100% Premium Cotton Fabric & Chiffon Dupatta (Unstitched)',
    craft: 'Traditional Hand Block Print',
    care: 'Dry Clean Recommended',
    color: 'Mustard Yellow & Red',
    colorHex: '#CA8A04',
    images: ['/images/products/long-kurti-1.jpg'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['3-Piece Set', 'Free Size', 'Unstitched', 'Handblock'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 52,
  },
  {
    id: 'saga-005',
    title: 'Dusty Rose & Sky Blue 3-Piece Unstitched Suit Set',
    subtitle: 'Dusty Rose Pink Unstitched Suit Fabric with Sky Blue Bottom & Sheer Dupatta',
    price: 1399,
    originalPrice: 1999,
    description: 'Serene elegance in pastel tones. Features dusty rose pink unstitched kurta fabric length adorned with floral jaal embroidery, paired with contrasting sky blue bottom material and a delicate border dupatta.',
    fabric: '100% Soft Mulmul Pure Cotton (Unstitched)',
    craft: 'Jaal Embroidery & Handwork',
    care: 'Gentle Hand Wash Cold',
    color: 'Dusty Rose & Sky Blue',
    colorHex: '#EC4899',
    images: ['/images/products/long-kurti-2.jpg'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['3-Piece Set', 'Free Size', 'Unstitched', 'Pastel Luxe'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 44,
  },
  {
    id: 'saga-006',
    title: 'Sky Blue Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Refreshing Sky Blue Pure Cotton Suit Fabric with White Geometric Chikankari Embroidery & Dupatta',
    price: 1399,
    originalPrice: 1999,
    description: 'Breathe timeless grace with this refreshing Sky Blue 3-Piece Chikankari Suit Set. Features intricate white geometric jaal threadwork across the bodice, matching bottoms, and an airy embroidered dupatta. 100% breathable pure cotton.',
    fabric: '100% Pure Cotton with Mulmul Dupatta (3-Piece Unstitched)',
    craft: 'Authentic Lucknowi Chikankari',
    care: 'Gentle Hand Wash or Dry Clean',
    color: 'Sky Blue & White',
    colorHex: '#38BDF8',
    images: ['/images/products/long-kurti-3.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['Bestseller', '3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 38,
  },
  {
    id: 'saga-007',
    title: 'Royal Lavender Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Enchanting Lavender Pure Cotton Fabric Set with Delicate White Chikankari Threadwork',
    price: 1449,
    originalPrice: 2099,
    description: 'Exude regal calm with this Royal Lavender Chikankari 3-Piece Set. Features delicate floral jaal embroidery, coordinating straight pants material, and a soft matching dupatta. Customizable to any silhouette.',
    fabric: '100% Premium Cotton with Lightweight Dupatta (3-Piece Unstitched)',
    craft: 'Traditional Hand Chikankari',
    care: 'Gentle Cold Wash',
    color: 'Lavender & White',
    colorHex: '#818CF8',
    images: ['/images/products/long-kurti-4.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['Royal Edit', '3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 42,
  },
  {
    id: 'saga-008',
    title: 'Peacock Teal Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Rich Peacock Teal Kurta Fabric with All-over Geometric Chikankari Work & Dupatta',
    price: 1399,
    originalPrice: 1999,
    description: 'A vibrant jewel tone suit set crafted from pure cotton, detailed with all-over intricate white Chikankari lattice work on the kurta, matching trouser fabric, and a featherlight bordered dupatta.',
    fabric: '100% Breathable Cotton (3-Piece Unstitched Set)',
    craft: 'Lucknowi Jaal Chikankari',
    care: 'Gentle Hand Wash Cold',
    color: 'Peacock Teal & White',
    colorHex: '#0D9488',
    images: ['/images/products/long-kurti-5.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 4.8,
    reviewsCount: 31,
  },
  {
    id: 'saga-009',
    title: 'Scarlet Crimson Red Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Festive Scarlet Red Cotton Suit with Floral Neckline & All-over Booti Chikankari Embroidery',
    price: 1449,
    originalPrice: 2099,
    description: 'Celebrate festive traditions in this rich Scarlet Crimson Red Chikankari Suit Set. Features an ornate floral neck yoke, scattered floral booti embroidery, matching bottom material, and an ethereal sheer dupatta with scalloped borders.',
    fabric: '100% Pure Fine Cotton & Organza Silk Blend Dupatta',
    craft: 'Intricate Floral Chikankari & Bakhiya Work',
    care: 'Dry Clean Recommended',
    color: 'Scarlet Red & White',
    colorHex: '#DC2626',
    images: ['/images/products/long-kurti-6.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['Festive Edit', '3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 57,
  },
  {
    id: 'saga-010',
    title: 'Mauve Orchid Pink Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Graceful Mauve Pink Cotton Set with Fine Floral Hand Embroidery & Sheer Dupatta',
    price: 1399,
    originalPrice: 1999,
    description: 'An elegant pastel ensemble in dusty mauve pink. Features fine floral Chikankari motifs along the front panel, sleeve hems, paired with coordinating bottoms and a flowing border dupatta.',
    fabric: '100% Soft Mulmul Pure Cotton (3-Piece Unstitched Set)',
    craft: 'Handcrafted Chikankari Embroidery',
    care: 'Gentle Hand Wash Cold',
    color: 'Mauve Pink & White',
    colorHex: '#F472B6',
    images: ['/images/products/long-kurti-7.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 35,
  },
  {
    id: 'saga-011',
    title: 'Aqua Marine Turquoise Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Vibrant Aqua Blue-Green Suit Fabric with Exquisite Floral Threadwork & Dupatta',
    price: 1399,
    originalPrice: 1999,
    description: 'Light up your summer and festive wardrobe with this Aqua Marine Chikankari set. Adorned with delicate floral jaal needlework, matching bottoms, and an airy embroidered dupatta.',
    fabric: '100% Pure Cotton with Breathable Sheer Dupatta',
    craft: 'Lucknowi Floral Chikankari',
    care: 'Gentle Cold Wash',
    color: 'Aqua Turquoise & White',
    colorHex: '#2DD4BF',
    images: ['/images/products/long-kurti-8.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 29,
  },
  {
    id: 'saga-012',
    title: 'Blush Coral Pink Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Vibrant Coral Rose Cotton Fabric Set with Dense Floral Chikankari Embroidery',
    price: 1399,
    originalPrice: 1999,
    description: 'Charming blush coral pink unstitched suit fabric embellished with dense floral bootas and an embroidered neckline. Includes unstitched bottom fabric and a matching bordered dupatta.',
    fabric: '100% Pure Cotton Fabric (3-Piece Unstitched Set)',
    craft: 'Authentic Hand Chikankari',
    care: 'Gentle Hand Wash Cold',
    color: 'Blush Coral Pink & White',
    colorHex: '#FB7185',
    images: ['/images/products/long-kurti-9.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['Festive Edit', '3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 4.8,
    reviewsCount: 27,
  },
  {
    id: 'saga-013',
    title: 'Ivory Cream Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Timeless Ivory Cream Pure Cotton Fabric with Subtle Tonal Chikankari Threadwork',
    price: 1449,
    originalPrice: 2099,
    description: 'Pure understated royalty. Crafted in soothing ivory cream cotton with tone-on-tone fine Chikankari needlecraft, matched with coordinating pant fabric and a sheer dupatta with border detailing.',
    fabric: '100% Premium Organic Cotton & Mulmul Dupatta',
    craft: 'Tonal Lucknowi Resham Chikankari',
    care: 'Dry Clean or Gentle Hand Wash',
    color: 'Ivory Cream & White',
    colorHex: '#FDFBF7',
    images: ['/images/products/long-kurti-10.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['Royal Edit', '3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 64,
  },
  {
    id: 'saga-014',
    title: 'Sage Olive Green Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Earthy Olive Green Cotton Set with Intricate White Jaal Embroidery & Dupatta',
    price: 1399,
    originalPrice: 1999,
    description: 'A serene earthy olive green 3-piece suit set featuring exquisite white Chikankari threadwork across the neckline and front length, paired with plain bottoms and a lightweight dupatta.',
    fabric: '100% Pure Breathable Cotton (3-Piece Unstitched Set)',
    craft: 'Jaal Chikankari Needlework',
    care: 'Gentle Hand Wash Cold',
    color: 'Sage Olive Green & White',
    colorHex: '#84CC16',
    images: ['/images/products/long-kurti-11.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 33,
  },
  {
    id: 'saga-015',
    title: 'Pristine Pearl White Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Classic Monochromatic White on White Chikankari Pure Cotton Suit Set & Dupatta',
    price: 1449,
    originalPrice: 2099,
    description: 'The quintessential Lucknowi heirloom. Pristine white-on-white Chikankari embroidery handcrafted on ultra-soft pure cotton fabric, accompanied by matching white trouser length and an embroidered sheer dupatta.',
    fabric: '100% Superfine Pure Cotton (3-Piece Unstitched Set)',
    craft: 'Classic White-on-White Lucknowi Chikankari',
    care: 'Gentle Hand Wash in Cold Water',
    color: 'Pristine White',
    colorHex: '#FFFFFF',
    images: ['/images/products/long-kurti-12.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['Bestseller', 'Royal Edit', '3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 89,
  },
  {
    id: 'saga-016',
    title: 'Rani Magenta Pink Chikankari 3-Piece Unstitched Suit Set',
    subtitle: 'Radiant Rani Pink Suit Fabric with White Chikankari Floral Vines & Dupatta',
    price: 1399,
    originalPrice: 1999,
    description: 'Dazzle in vibrant celebratory shades with this Rani Magenta Chikankari suit set. Boasts intricate floral vine motifs on the kurti panel, unstitched salwar/pants fabric, and an ornate dupatta.',
    fabric: '100% Premium Cotton & Flowing Chiffon Dupatta',
    craft: 'Authentic Lucknowi Hand Embroidery',
    care: 'Gentle Hand Wash or Dry Clean',
    color: 'Rani Magenta Pink & White',
    colorHex: '#EC4899',
    images: ['/images/products/long-kurti-13.png'],
    sizes: ['Free Size (Unstitched)'],
    tags: ['Festive Edit', '3-Piece Set', 'Free Size', 'Unstitched', 'Chikankari'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 46,
  },
];
