import { Product } from '@/types';

export const PRODUCTS: Product[] = [
  {
    id: 'saga-001',
    title: 'Royal Indigo White Chikankari Short Kurti',
    subtitle: '100% Pure Cotton Short Tunic with Intricate Royal Blue Neck & Sleeve Embroidery',
    price: 1399,
    originalPrice: 1999,
    description: 'Elevate your daily ethnic look with this handcrafted Royal Indigo White Short Kurti. Cut from ultra-breathable pure cotton, featuring delicate royal blue Chikankari hand threadwork along the V-neckline, cuffs, and hem.',
    fabric: '100% Breathable Pure Cotton (Stitched Short Kurti)',
    craft: 'Authentic Lucknowi Chikankari Embroidery',
    care: 'Gentle Hand Wash in Cold Water',
    color: 'Pristine White & Royal Blue',
    colorHex: '#1E3A8A',
    images: ['/images/products/1.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['Bestseller', 'Short Kurti', 'Chikankari'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 48,
  },
  {
    id: 'saga-002',
    title: 'Midnight Blue Yoke Chikankari Short Kurti',
    subtitle: 'Crisp White Cotton Short Kurti with Deep Blue Floral Motif Embroidery',
    price: 1349,
    originalPrice: 1899,
    description: 'A classic summer staple featuring a rich midnight blue Chikankari embroidered yoke on crisp white cotton. Soft, airy, and effortlessly stylish when paired with denim jeans or cigarette pants.',
    fabric: '100% Breathable Pure Cotton (Stitched Short Kurti)',
    craft: 'Lucknowi Thread Needlework',
    care: 'Gentle Hand Wash Separately',
    color: 'White & Navy Blue',
    colorHex: '#1E293B',
    images: ['/images/products/2.jpeg'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['New Arrival', 'Short Kurti', 'Chikankari'],
    inStock: true,
    rating: 4.8,
    reviewsCount: 32,
  },
  {
    id: 'saga-003',
    title: 'Mint Emerald Chikankari Short Kurti',
    subtitle: 'Soft White Cotton Tunic with Refreshing Emerald Green Threadwork',
    price: 1449,
    originalPrice: 2099,
    description: 'Radiate fresh elegance with this Mint Emerald Chikankari Short Kurti. Meticulously embroidered with botanical green thread patterns on light-as-air pure cotton fabric.',
    fabric: '100% Soft Mulmul Pure Cotton (Stitched Short Kurti)',
    craft: 'Traditional Hand Chikankari',
    care: 'Gentle Hand Wash or Dry Clean',
    color: 'White & Emerald Green',
    colorHex: '#059669',
    images: ['/images/products/3.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['Festive Edit', 'Short Kurti', 'Chikankari'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 41,
  },
  {
    id: 'saga-004',
    title: 'Sunshine Yellow Chikankari Short Kurti',
    subtitle: 'Crisp White Cotton Short Kurti with Bright Yellow Floral Threadwork',
    price: 1399,
    originalPrice: 1999,
    description: 'Brighten up your wardrobe with our Sunshine Yellow Chikankari Short Kurti. Vibrant marigold yellow hand embroidery against soft white cotton creates a charming, joyful aesthetic.',
    fabric: '100% Premium Pure Cotton (Stitched Short Kurti)',
    craft: 'Hand Embroidered Chikankari',
    care: 'Hand Wash Cold',
    color: 'White & Sunshine Yellow',
    colorHex: '#EAB308',
    images: ['/images/products/4.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['Trending', 'Short Kurti', 'Chikankari'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 37,
  },
  {
    id: 'saga-005',
    title: 'Rose Gold Peach Chikankari Short Kurti',
    subtitle: 'Elegant Ivory Cotton Tunic with Soft Peach & Rose Thread Embroidery',
    price: 1449,
    originalPrice: 2099,
    description: 'Delicate pastel luxury for brunch dates and office wear. Features subtle peach resham threadwork hand-embroidered on soft white cotton tunic material.',
    fabric: '100% Pure Organic Cotton (Stitched Short Kurti)',
    craft: 'Lucknowi Resham Chikankari',
    care: 'Gentle Cold Wash',
    color: 'White & Soft Peach',
    colorHex: '#F97316',
    images: ['/images/products/5.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['Royal Edit', 'Short Kurti', 'Chikankari'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 29,
  },
  {
    id: 'saga-006',
    title: 'Sapphire Blue Regal Chikankari Short Kurti',
    subtitle: 'Classic Ivory Short Kurti with Detailed Sapphire Blue Paisley Accents',
    price: 1399,
    originalPrice: 1999,
    description: 'Intricate paisley and geometric lattice hand-embroidery in sapphire blue tones adorn this pure cotton short kurti. Designed for ultimate comfort and breezy elegance.',
    fabric: '100% Premium Cotton (Stitched Short Kurti)',
    craft: 'Handcrafted Chikankari Motif',
    care: 'Gentle Hand Wash',
    color: 'White & Sapphire Blue',
    colorHex: '#2563EB',
    images: ['/images/products/6.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['Bestseller', 'Short Kurti', 'Chikankari'],
    inStock: true,
    rating: 4.8,
    reviewsCount: 53,
  },
  {
    id: 'saga-007',
    title: 'Slate Powder Blue Chikankari Short Kurti',
    subtitle: 'Serene Powder Blue Cotton Tunic with Delicate White Hand Embroidery',
    price: 1499,
    originalPrice: 2199,
    description: 'A soothing pastel blue short kurti accented with pristine white Chikankari threadwork. Breathable, elegant, and versatile for all-day comfort.',
    fabric: '100% Soft Mulmul Pure Cotton (Stitched Short Kurti)',
    craft: 'Pure White Chikankari Threadwork',
    care: 'Gentle Cold Hand Wash',
    color: 'Powder Blue & White',
    colorHex: '#64748B',
    images: ['/images/products/7.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['Pastel Luxe', 'Short Kurti', 'Chikankari'],
    inStock: true,
    rating: 5.0,
    reviewsCount: 36,
  },
  {
    id: 'saga-008',
    title: 'Ocean Teal Chikankari Short Kurti',
    subtitle: 'Vibrant Teal Blue Cotton Short Tunic with Ornate White Chikankari',
    price: 1449,
    originalPrice: 2099,
    description: 'Make a bold statement with our Ocean Teal Chikankari Short Kurti. Striking teal cotton fabric paired with intricate white hand threadwork along the neckline and hem.',
    fabric: '100% Premium Pure Cotton (Stitched Short Kurti)',
    craft: 'Authentic Lucknowi Chikankari',
    care: 'Dry Clean or Cold Hand Wash',
    color: 'Ocean Teal & White',
    colorHex: '#0D9488',
    images: ['/images/products/8.png'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    tags: ['New Arrival', 'Short Kurti', 'Chikankari'],
    inStock: true,
    rating: 4.9,
    reviewsCount: 44,
  },
];

